### ISSUE TITLE
Signalr Epic

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-connect-signalr#8]
- [ ] - Code works, good tests & Reviewed
- [ ] - Docs look good & Reviewed
- [ ] - Example app looks good & Reviewed (Azure + SignalR)
       - FULL CRUD
- [ ] - Outline of article
- [ ] - Rough Draft
- [ ] - Final cut
